### PR TITLE
Fix lifespan function signature in the example

### PR DESCRIPTION
**Pull request by JonathanPlasse**
Add `app` argument as described in the [documentation](https://www.starlette.io/events/)

### CODE REVIEW

**Comment by empicano** [comment]
Good catch! 👍 I noticed the `contextlib` import was missing as well. Maybe we should write some tests for these examples one day 😄

**Comment by frederikaalund** [comment]
*I write here because it's the latest 1:1 point of contact between you and I.*

Jonatan, your recent PRs and comments are on point. 👍 By that I mean that your and my thoughts on the asyncio-mqtt development effort are aligned. As you've probably noticed yourself, asyncio-mqtt could use another developer/maintainer or two to keep up with the ever-changing world of python dev and the questions (issues on GitHub) that we get from the community.

**Do you want to join the asyncio-mqtt team as a maintainer?** There are no strings attached. You contribute just as much as you'd like (or not at all if you're busy with other things). Practically, you'll get push-without-PR rights that make it easier for you to contribute to asyncio-mqtt directly. Of course, you're welcome to contribute via the current PR-based workflow and I'll gadly review any PRs that you send that way. 😄 It's completely up to you.

Thanks again for your contributions to asyncio-mqtt thus far!

**Comment by JonathanPlasse** [comment]
> _I write here because it's the latest 1:1 point of contact between you and I._
> 
> Jonathan, your recent PRs and comments are on point. 👍 By that I mean that your and my thoughts on the asyncio-mqtt development effort are aligned. As you've probably noticed yourself, asyncio-mqtt could use another developer/maintainer or two to keep up with the ever-changing world of python dev and the questions (issues on GitHub) that we get from the community.
> 
> **Do you want to join the asyncio-mqtt team as a maintainer?** There are no strings attached. You contribute just as much as you'd like (or not at all if you're busy with other things). Practically, you'll get push-without-PR rights that make it easier for you to contribute to asyncio-mqtt directly. Of course, you're welcome to contribute via the current PR-based workflow and I'll gadly review any PRs that you send that way. 😄 It's completely up to you.
> 
> Thanks again for your contributions to asyncio-mqtt thus far!

@frederikaalund, yes I am interested to join the organisation.

**Comment by frederikaalund** [comment]
Great to hear that! I just added you as a maintainer of asyncio-mqtt. Welcome aboard. 😄👍 

Again, there are no strings attached. You contribute/maintain to the extend that you feel comfortable.

**Comment by JonathanPlasse** [comment]
Thank you :smile:

**Pull request merged**
