### PR TITLE
added exception handling in callback for loop_read and loop_write

### PR DESCRIPTION
**Pull request by gilbertsmink**
Proposed fix for issue #35

### CODE REVIEW

**Comment by frederikaalund** [comment]
Hi Gilbert. Thanks for making this pull request. :+1: 

I can see that there are some conflicts. It's probably because we added types to asyncio-mqtt recently. Can you try to rebase your changes on top of the latest commit on the master branch?

Otherwise, I think that this PR looks good. :) I'd like to see a comment at the `try..except` block that explains why we need it. Something like: "`loop_read` may raise an exception such as `BadPipe`. It's usually a sign that the underlying connection broke. If this happens, we disconnect right away."

**Comment by gilbertsmink** [comment]
ok updated the pull request

**Comment by frederikaalund** [comment]
Thanks for the effort, Gilbert. :+1: 

There are still some conflicts that prevent the merge. I see this in the GitHub UI:
image

Looks like you have several commits on this branch now. Some of them are unrelated to your fix. That's probably what caused the conflicts.

I think that we only need commit b4170fc873994ec129efc50f3512662def108836 of yours and not the rest.

---

I see three options here:
 1. You fix your pull request branch so that it only contains commit b4170fc873994ec129efc50f3512662def108836
 2. You close this pull request and create a new one that only contains commit b4170fc873994ec129efc50f3512662def108836
 3. I apply commit b4170fc873994ec129efc50f3512662def108836 manually on top of master. I'll give you full credit in the changelog of course.

Which option should we pursue? :)

**Comment by gilbertsmink** [comment]
Ow Github is telling me there are no conflicts, but I hardly understand how rebase actually works. I will try again from skratch, because I have to climb this Git learning curve at some point, might as well start not

**Pull request closed without merging**
