### PR TITLE
Make connect() non-blocking

### LINKED ISSUE #22: Client.connect() blocks the event loop
```
async with Client("10.10.0.1") as client:
    ...
```
blocks the event loop for 30 seconds. The source code appears to call the paho client connect() directly.

### PR DESCRIPTION
**Pull request by oholsen**
Resolves #22.

### CODE REVIEW

**Comment by frederikaalund** [comment]
Hi Øystein, thanks for the pull request. Let me have a look. :)

I did not realize that `paho.Client.connect` is blocking. Good catch!

I had a brief look at `paho.Client.connect_async` that sounds promising but unfortunately doesn't work for our use case. At least not without reimplementing a significant portion of paho.mqtt ourselves.

In any case, seems to me like it's the right approach to simply execute `paho.Client.connect_async` in another thread (as done in your pull request).

Good to see a test as well. :+1: We need more pull requests in that area.

Thanks for you contribution. If you want, you can add your change to the changelog and attribute it to yourself.

**Comment by oholsen** [comment]
@frederikaalund Will there be a release soon that incorporates this and other fixes?

**Comment by frederikaalund** [comment]
I plan to close some of the issues this week. Afterwards, I'll make a release. :)

**Comment by oholsen** [comment]
Great! 😀

**Comment by frederikaalund** [comment]
I just released v0.8.1 :+1:

Sorry about the delay.

**Comment by oholsen** [comment]
Thanks! 😀

**Pull request merged**
