### PR TITLE
Change publishing tooling

### LINKED ISSUE #142: Replace setup.py by pyproject.toml
`pyproject.toml` is the new standard for building a package.

### PR DESCRIPTION
**Pull request by JonathanPlasse**
Close #142 and #143

- [x] Change from `setup.py` to `pyproject.toml`.
- [x] Use `setuptools-scm` to generate the version based on tags.
- [x] Add continuous integration to publish `asyncio-mqtt` to PyPI when creating a release.
- [x] Update the changelog to prepare for a release

### CODE REVIEW

**Comment by JonathanPlasse** [comment]
@empicano, is it ok with you to add you as a maintainer in the metadata of `asyncio-mqtt`?
@frederikaalund, can you double-check?

**Comment by empicano** [comment]
> @empicano, is it ok with you to add you as a maintainer in the metadata of `asyncio-mqtt`?

Sure! 👍 

Lots of automation we're getting here, very cool!

**Review by frederikaalund — APPROVED** [review]
LGTM! :+1: Super to see all these improvements to our tooling. Sure beats my previous manual use of `twine`. :smile: 

Nice use of `[tool.setuptools_scm]` to set the version.

Really great to see that you updated the changelog as well. :+1: That's what takes the longest for me whenever I do a release.

~Frederik

**Comment by JonathanPlasse** [comment]
@empicano, @frederikaalund, We should update the changelog in each pull request instead of all at once before a release. I added it to `CONTRIBUTING.md`.
Also, should we deprecate the `master` branch in favor of the `main` branch?

**Comment by frederikaalund** [comment]
> We should update the changelog in each pull request instead of all at once before a release. I added it to CONTRIBUTING.md.

I agree. :+1: Should be a requirement of each PR. We do have to be a bit lenient with external users in practice, though. Otherwise, the barrier to contribution becomes too high.

> Also, should we deprecate the master branch in favor of the main branch?

Sure, why not. :)

**Comment by JonathanPlasse** [comment]
@frederikaalund, can you remove the tag v0.14.0, the publishing did not work as my email address was not considered valid.

**Comment by frederikaalund** [comment]
> @frederikaalund, can you remove the tag v0.14.0? The publishing did not work as my email address was not considered valid.

Done as per the other thread.

**Pull request merged**
