### PR TITLE
Fix autocomplete for _outgoing_call decorator

### PR DESCRIPTION
**Pull request by JonathanPlasse**
The signature of the `Client.subscibe()` for example only displayed
`(...) -> Coroutine[Any, Any, Tuple[int] | List[ReasonCodes]]` 
instead of
`(topic: str | Tuple[str, SubscribeOptions] | List[Tuple[str, SubscribeOptions]] | List[Tuple[str, int]], qos: int = ..., options: SubscribeOptions | None = ..., properties: Properties | None = ..., *args: Any, timeout: int = ..., **kwargs: Any) -> Coroutine[Any, Any, Tuple[int] | List[ReasonCodes]]`

### CODE REVIEW

**Comment by frederikaalund** [comment]
Thanks for taking a deep look at the typings. 👍 

I like this direction with `ParamSpec` and friends. It's the way to go.

My only comment is that you should conditionally import `ParamSpec`:
 * from `typing` if we are on 3.10 or later.
 * from `typing_extensions` otherwise.

This way, typing-extensions remains an *optional* dependency (and not a requirement) depending on the python version. See https://github.com/sbtinstruments/asyncio-mqtt/blob/master/setup.py#L40 for details.

**Comment by JonathanPlasse** [comment]
Done

**Comment by JonathanPlasse** [comment]
When do you think you will release a new version?

**Comment by frederikaalund** [comment]
> When do you think you will release a new version?

I can do that tomorrow. :)

Thank you for your contribution to asyncio-mqtt.

**Comment by JonathanPlasse** [comment]
You are welcome!

**Comment by frederikaalund** [comment]
v0.13.0 is out now. 👍

**Pull request merged**
