### PR TITLE
Publisher/Subscribe example also for JSON data and ProtocolVersion in the init

### PR DESCRIPTION
**Pull request by tropxy**
docs: Added a Publisher example, how to handle with the Client arguments and added an example of how to deal with JSON data; included ProtocolVersion in the __init__.py so that we can directly summon the Enum from the package import

This addresses #63

### CODE REVIEW

**Comment by frederikaalund** [comment]
Looks good! :+1: 

I have two requests:
  * Let's move the examples to an `/examples` folder to not clutter `README.md`. I like to keep the readme simple. :)
  * I like the change to `__init__.py`. :+1: It's unrelated to the docs, though, so can you move it into a separate commit?

Does it make sense?

**Comment by tropxy** [comment]
Yup, it all makes sense. I initially added an examples folder, but then usually one creates python scripts to exemplify whatever is the used case you trying to exemplify and in this case I thought it is just easier to show in a Markdown file how it works and add comments there as necessary. Do you think it would make sense to create an Examples.md? Or you really prefer to have scripts?

**Comment by frederikaalund** [comment]
Both `.py` and `.md` works for me. :+1: Whatever you prefer. This is the start of the documentation that we don't currently have. :))

**Comment by tropxy** [comment]
> Both `.py` and `.md` works for me. 👍 Whatever you prefer. This is the start of the documentation that we don't currently have. :))

I hope it looks better now

**Comment by frederikaalund** [comment]
Looks good to me. Thanks for your contribution to asyncio-mqtt. :) :+1:

**Comment by tropxy** [comment]
My pleasure! I hope we can do like a proper doc page in the future ;)

**Pull request merged**
