### PR TITLE
Add sphinx documentation site

### PR DESCRIPTION
**Pull request by empicano**
I set up Sphinx!

The documentation is live at [https://sbtinstruments.github.io/asyncio-mqtt](https://sbtinstruments.github.io/asyncio-mqtt). I thought about deploying to ReadTheDocs, but they show ads, so I stuck with GitHub Pages, even though the URL is not that nice.

It's still a bit rough on the edges. For now, I only copied the "Advanced usage" Section.

I want to clean up the `README` still (to not have duplication anywhere), add an introduction to the Sphinx docs, and integrate the information from the `examples` folder.

Let me know what you think! 😊

~Felix

### CODE REVIEW

**Comment by JonathanPlasse** [comment]
The section Topic filter does not contain filters with wildcards which could make believe that it is not possible.

**Comment by frederikaalund** [comment]
It looks really good! A very nice initiative, indeed. 👍 

I like the simplicity of it as well. After all, asyncio-mqtt is a *tiny* wrapper around paho-mqtt.

Some suggestions for further work:

 * Add a "repo" link back to GitHub.
 * Similarly, add an "issue tracker" link to our GitHub-based issues page.

**Comment by empicano** [comment]
Thanks for the feedback! 😎

> The section Topic filter does not contain filters with wildcards which could make believe that it is not possible.

You're right 👍 The new example for #147 includes wildcards.

> Some suggestions for further work: [...]

Great ideas, done!

**Comment by JonathanPlasse** [comment]
Awesome :tada:

**Comment by empicano** [comment]
Thank you! 😊

**Comment by frederikaalund** [comment]
Looks great! 😄 Well done. 👍 We really needed better docs sooner rather than later.

**Pull request merged**
