### PR TITLE
Fix socket options for websocket transport

### PR DESCRIPTION
**Pull request by chmielowiec**
Fixing the following error:

```
  File /venv/lib/python3.8/site-packages/asyncio_mqtt/client.py", line 81, in connect
    self._client.socket().setsockopt(socket.SOL_SOCKET, socket.SO_SNDBUF, 2048)
AttributeError: 'WebsocketWrapper' object has no attribute 'setsockopt'
```

### CODE REVIEW

**Comment by frederikaalund** [comment]
Hi Robert. Thanks for the pull request. :+1:  Let me have a look.

Nice find. I never tested this with a WebSocket-wrapped connection.

I like the fix in general. One comment though: Let's use `isinstance` instead. I think that's more idiomatic. What do you think?

**Comment by chmielowiec** [comment]
Thanks for quick review! Changed according to your proposal, thanks :-) (still learning python)

**Comment by frederikaalund** [comment]
Super. :+1: Let me know how the test goes. I'll merge it afterwards.

**Comment by chmielowiec** [comment]
Tested, and of course it works perfectly, thanks for the tip!

**Pull request merged**
