### PR TITLE
Added documentation for tls_set in README.md

### PR DESCRIPTION
**Pull request by Sohaib90**
I just wanted to ask for improvements and suggestions when adding the recent changes to the README.md
If this is alright (for now, just tls_set example added) I can add the proxy settings as well

### CODE REVIEW

**Comment by Sohaib90** [comment]
Hmmm, do I have to use black on the README.md or just the example code part and then commit that?

**Comment by frederikaalund** [comment]
Just the example code, thanks. :) It formats python code in a standard way. IMHO, it's a good idea to run it on all python code that goes into this repo.

**Comment by Sohaib90** [comment]
Just added the formatted example code. If this is alright, I would also like to add the `proxy_set` information and commit that in this PR

**Comment by frederikaalund** [comment]
Looks great, thanks!

> If this is alright, I would also like to add the proxy_set information and commit that in this PR

Please, by all means go ahead. :)

**Comment by Sohaib90** [comment]
@frederikaalund I have added the documentation for the proxy settings as well. It is complete now

**Comment by frederikaalund** [comment]
LGTM. This will definitely help our users since we were pretty light on the documentation beforehand. Thanks again for your contribution to asyncio-mqtt. :+1:

**Comment by Sohaib90** [comment]
It was my pleasure :) 
Might contribute in the future as well

**Pull request merged**
