### PR TITLE
Add tests and coverage

### PR DESCRIPTION
**Pull request by JonathanPlasse**
Add tests and coverage for Continuous Integration.

### CODE REVIEW

**Comment by JonathanPlasse** [comment]
@frederikaalund, can you activate  [Codecov](https://github.com/apps/codecov)?

**Comment by JonathanPlasse** [comment]
I had to merge to activate the new workflow.

**Comment by JonathanPlasse** [comment]
Codecov still need to be activated.

**Comment by JonathanPlasse** [comment]
The tests and coverage are now working! :tada:

**Comment by empicano** [comment]
Very nice! 🎉

**Pull request merged**
